# Generated by Django 6.0.6 on 2026-06-15 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bookkeeper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('published_date', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('cbz', 'CBZ / Comic Book Archive')], max_length=10)),
                ('file', models.FileField(upload_to=bookkeeper.models.book_upload_path)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=bookkeeper.models.cover_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('position', models.TextField()),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookkeeper.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.TextField()),
                ('end_position', models.TextField()),
                ('text', models.TextField()),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('orange', 'Orange')], default='yellow', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bookkeeper.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book', 'page_number', 'start_position'],
            },
        ),
        migrations.CreateModel(
            name='ReaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveSmallIntegerField(default=16)),
                ('font_family', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-serif'), ('monospace', 'Monospace'), ('Georgia, serif', 'Georgia'), ("'Palatino Linotype', serif", 'Palatino'), ("'Open Sans', sans-serif", 'Open Sans')], default='serif', max_length=50)),
                ('line_height', models.FloatField(default=1.6)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('sepia', 'Sepia'), ('dark', 'Dark')], default='light', max_length=20)),
                ('column_width', models.CharField(choices=[('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide')], default='normal', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reader settings',
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('percentage', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='bookkeeper.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_read', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='bookkeeper.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_last_read', '-date_added'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='bookkeeper__title_8e8dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='bookkeeper__author_7607e5_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['format'], name='bookkeeper__format_e468b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
    ]
