# Generated by Django 6.0.6 on 2026-06-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spine_index', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('html', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=16)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bookkeeper.book')),
            ],
            options={
                'ordering': ['spine_index'],
                'unique_together': {('book', 'spine_index')},
            },
        ),
    ]
