# Generated by Django 6.0.6 on 2026-06-17 08:53

from django.db import migrations, models

import bookkeeper.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='cover_override',
            field=models.ImageField(blank=True, null=True, upload_to=bookkeeper.models.user_cover_upload_path),
        ),
    ]
