# Generated by Django 6.0.6 on 2026-06-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0003_userbook_cover_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('cbz', 'CBZ / Comic Book Archive'), ('cbr', 'CBR / Comic Book Archive (RAR)')], max_length=10),
        ),
    ]
