# Generated by Django 6.0.6 on 2026-06-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0005_add_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
