# Generated by Django 6.0.6 on 2026-06-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0006_add_amazon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='readersettings',
            name='fit_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readersettings',
            name='pdf_zoom',
            field=models.FloatField(default=1.0),
        ),
    ]
